### ISSUE TITLE
Export in JSON format

### ISSUE THREAD

**Issue by lwbaqueros** [otacke/h5pxapikatchu#19]
Hi
Is it possible to export the data in a JSON file instead of CSV file?

**Comment by otacke** [comment]
@lwbaqueros Currently not, but you can use the `h5pxapikatchu_insert_data_xapi` filter to retrieve the xAPI statement (which is a JSON object) and process it further.

**Comment by lwbaqueros** [comment]
Thanks, @otacke, for your response and plugin. If I understood correctly, I have to check this option:
![image](https://user-images.githubusercontent.com/46763074/121660514-a1ebd780-caa3-11eb-9ce8-712b1a99d6e2.png)
and then I can use the data displayed in the `xAPI` column (in the csv file), which will contain the info in the JSON format.

By the way, and sorry to ask by this means, but It seems that WP does not support more the plugin you recommended for sending the xAPI statements to an LRS `WP-H5P-xAPI`. do you know another way to accomplish it?

**Comment by otacke** [comment]
@lwbaqueros That's one way, yes. But I was referring to the [action/filter system that WordPress provides](https://developer.wordpress.org/plugins/hooks/). It allows you to hook into function performed by plugins and process and do your own things without the need to change the original code. Some people do that to get the data directly instead of downloading them via the export button. Please cmp. https://github.com/otacke/h5pxapikatchu/pull/14 for instance.

The wp-h5p-xapi plugin can still be obtained from https://github.com/tunapanda/wp-h5p-xapi, but it doesn't seem to be maintained anymore (despite some flaws) and that's why it was unlisted from the WordPress plugin repository.

**Comment by lwbaqueros** [comment]
Thanks. I think that is what I need.
